VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/8"
  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "3072"]
  end
  config.vm.network :private_network, ip: '192.168.115.16'
  config.vm.network :forwarded_port, guest: 22, host: 22016, id: 'ssh'
end
