kind: pipeline
type: docker
name: flake8

steps:
- name: flake8
  image: pyrocko-nest
  pull: never
  commands:
  - flake8 src test examples setup.py

---

kind: pipeline
type: docker
name: docs

steps:
- name: build
  image: pyrocko-docs
  pull: never
  commands:
  - python3 setup.py install && cd doc && make html

- name: stage
  image: pyrocko-aux
  pull: never
  commands:
  - maintenance/drone-rsync.sh doc/build/html/ ${DRONE_COMMIT}/doc/
  environment:
    RSYNC_HOST:
      from_secret: rsync-host
    RSYNC_USER:
      from_secret: rsync-user
    RSYNC_KEY:
      from_secret: rsync-key

---

kind: pipeline
type: docker
name: pip-wheels

trigger:
  branch:
  - candidate
  - pip-wheels

steps:
- name: build-manylinux1_x86_64
  image: quay.io/pypa/manylinux1_x86_64
  commands:
  - maintenance/pip/build_wheels.sh
  environment:
    PLAT: manylinux1_x86_64

- name: test-manylinux1_x86_64
  image: pyrocko-nest
  pull: never
  commands:
  - apt-get -y update
  - apt-get -y install python3-pip
  - pip3 install -r requirements-all.txt
  - pip3 install -f wheels --no-index pyrocko
  - xvfb-run -s '-screen 0 640x480x24' python3 -m nose test

- name: stage-manylinux1_x86_64
  image: pyrocko-aux
  pull: never
  commands:
  - maintenance/drone-rsync.sh wheels/ ${DRONE_COMMIT}/wheels/
  environment:
    RSYNC_HOST:
      from_secret: rsync-host
    RSYNC_USER:
      from_secret: rsync-user
    RSYNC_KEY:
      from_secret: rsync-key

---

kind: pipeline
type: docker
name: tests-base

steps:
- name: tests-base
  image: pyrocko-nest
  pull: never
  commands:
  - python3 setup.py install -f
  - pip3 install utm
  - pip3 install git+https://github.com/pyrocko/kite
  - pip3 install obspy
  - python3 -m nose test.base

---

kind: pipeline
type: docker
name: tests-gf

steps:
- name: tests-gf
  image: pyrocko-nest
  pull: never
  commands:
  - python3 setup.py install -f
  - pip3 install utm
  - pip3 install git+https://github.com/pyrocko/kite
  - pip3 install obspy
  - python3 -m nose test.gf

---

kind: pipeline
type: docker
name: tests-examples

steps:
- name: tests-examples
  image: pyrocko-nest
  pull: never
  commands:
  - python3 setup.py install -f
  - pip3 install utm
  - pip3 install git+https://github.com/pyrocko/kite
  - pip3 install obspy
  - python3 -m nose test.examples

---

kind: pipeline
type: docker
name: tests-gui

steps:
- name: tests-gui
  image: pyrocko-nest
  pull: never
  commands:
  - python3 setup.py install -f
  - pip3 install obspy
  - xvfb-run -s '-screen 0 640x480x24' python3 -m nose test.gui test.base.test_obspy_compat:ObsPyCompatTestCase.test_obspy_fiddle test.base.test_obspy_compat:ObsPyCompatTestCase.test_obspy_snuffle

---

kind: pipeline
type: docker
name: coverage

trigger:
  branch:
  - candidate
  - coverage

steps:
- name: build
  image: pyrocko-nest
  pull: never
  commands:
  - python3 setup.py install -f
  - pip3 install utm
  - pip3 install git+https://github.com/pyrocko/kite
  - pip3 install obspy
  - xvfb-run -s '-screen 0 640x480x24' python3 -m nose --with-coverage test
  - python3 -m coverage html

- name: stage
  image: pyrocko-aux
  pull: never
  commands:
  - maintenance/drone-rsync.sh htmlcov/ ${DRONE_COMMIT}/coverage/
  environment:
    RSYNC_HOST:
      from_secret: rsync-host
    RSYNC_USER:
      from_secret: rsync-user
    RSYNC_KEY:
      from_secret: rsync-key
