# .prettierrc or .prettierrc.yaml
trailingComma: 'es5'
tabWidth: 4
semi: false
singleQuote: true
overrides:
  - files: '*.html'
    options:
      parser: 'vue'
  - files: '*.yaml'
    options:
      tabWidth: 2
