FROM debian:12
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y rsync git python3-pip xvfb libgles2-mesa-dev libfontconfig1 libxrender1 libxkbcommon-x11-0 python3-requests
