VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "AndrewDryga/vagrant-box-osx"
  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "3072"]
  end
  #config.vm.network :private_network, ip: '192.168.115.112'
  #config.vm.network :forwarded_port, guest: 22, host: 22112, id: 'ssh'
  config.vm.synced_folder ".", "/vagrant",
    type: "rsync",
    rsync__chown: false
end
