VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "../../../test/data", "/pyrocko-test-data"
  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "3072"]
  end
  config.vm.network :private_network, ip: '192.168.115.8'
  config.vm.network :forwarded_port, guest: 22, host: 22008, id: 'ssh'
end
