VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "opensuse/openSUSE-42.2-x86_64"
  config.vm.synced_folder "../../../test/data", "/pyrocko-test-data"
  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "3072"]
  end
end
