#!/usr/bin/env python

from pyrocko import io
import sys
import os

if len(sys.argv) < 3:
    sys.exit('usage mseed2ascii <inputfiles> ... <outputdirectory>')

in_filenames = sys.argv[1:-1]
out_dirname = sys.argv[-1]
if os.path.exists(out_dirname) and not os.path.isdir(out_dirname):
    sys.exit('output path must be a direcory')

fn_tmpl = 'trace_%(network)s-%(station)s-%(location)s-%(channel)s_%(tmin)s.txt'

for fn in in_filenames:
    traces = io.load(fn, format='mseed')
    for tr in traces:
        io.save(tr, os.path.join(out_dirname, fn_tmpl))
