#!/usr/bin/env python

from pyrocko import serial_hamster, io
import os
from subprocess import Popen, PIPE

pjoin = os.path.join


        

source = Popen(['./test_datasource.py'], stdout=PIPE)

hamster = Hamster(path='testdata', port='/dev/ttyUSB0', in_file=source.stdout)
hamster.start()
