#!/usr/bin/env python

'''Moment tensor calculator.'''

# Copyright (c) 2010, Sebastian Heimann <sebastian.heimann@zmaw.de>
#
# This file is part of pyrocko. For licensing information please see the file 
# COPYING which is included with pyrocko.

import os, sys, signal, logging
import numpy as num
from optparse import OptionParser

from PyQt4.QtCore import *
from PyQt4.QtGui import *

class MySnuffler(QApplication):
    
    def __init__(self, *args):
        apply(QApplication.__init__, (self,) + args)
        
                        
        self.win = QMainWindow()
       # self.win.setCentralWidget( self.pile_viewer )
        self.win.show()

        sb = self.win.statusBar()
        sb.clearMessage()
        sb.showMessage('Welcome to Momo!')

        self.connect(self, SIGNAL("lastWindowClosed()"), self.myquit)
        signal.signal(signal.SIGINT, self.myquit)

    def myquit(self, *args):
        self.quit()
    
def main(args):
    
    app = MySnuffler(args)
    app.exec_()
    
    sys.exit()

if __name__=="__main__":
    main(sys.argv)
