FROM ubuntu:20.04

RUN apt-get update -y
RUN apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y debhelper-compat dh-python python3-all python3-dev python3-numpy git python3-setuptools debmake
